apply plugin: 'java-library'

group = 'voc-insights-impl'

dependencies {
    testImplementation project(':voc-service-common').sourceSets.test.output
    testImplementation project(':voc-service-insights:voc-insights-data-impl').sourceSets.main.output
    testImplementation project(':voc-service-insights:voc-insights-alert-impl').sourceSets.main.output
    testImplementation project(':voc-service-third:voc-trhird-feishu-impl').sourceSets.main.output
    testImplementation project(':voc-service-third:voc-trhird-api').sourceSets.main.output
    api project(':voc-service-common')
    api project(':voc-service-components:voc-cmps-mybatis')
    api project(':voc-service-components:voc-cmps-redis')
    //api project(':voc-service-components:voc-cmps-swagger')
    api project(':voc-service-components:voc-cmps-minio')
    api project(':voc-service-insights:voc-insights-api')
    api project(':voc-service-insights:voc-insights-common')
    api project(':voc-service-security:voc-security-client')
    api project(':voc-service-bizlogs:voc-bizlogs-api')
    api project(':voc-service-security:voc-security-api')
    api project(':voc-service-third:voc-trhird-api')
    api project(':voc-service-config')
    api project(':voc-service-components:voc-cmps-kafka')
    api project(':voc-service-analysis:voc-analysis-api')

//    compileOnlyApi project(':voc-service-insights:voc-insights-account-impl')

    compileOnly('org.springframework.boot:spring-boot-starter-web')
    api('org.springframework.cloud:spring-cloud-starter-bootstrap')

    api ("com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery")
    api ("com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config")
    api('com.github.pagehelper:pagehelper-spring-boot-starter')
    api('org.springframework.boot:spring-boot-starter-validation')

    // https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-config-server
//    implementation 'org.springframework.cloud:spring-cloud-config-server:5.0.0-M4'

//    implementation('org.springframework.cloud:spring-cloud-dependencies:2023.0.6')
}
