

-- SHOW ROUTINE LOAD FOR example_tbl2_ordertest9
-- SHOW ROUTINE LOAD TASK WHERE JobName = "example_tbl2_ordertest9"
-- PAUSE  ROUTINE LOAD FOR  ays_meta_data_analysis_kafka_test1
--   RESUME  ROUTINE LOAD FOR  ays_meta_data_analysis_kafka_20240712_c_1
-- STOP ROUTINE LOAD FOR ays_meta_data_analysis_kafka_20240712_c_1


CREATE ROUTINE LOAD report_model_tags_result_data_risk_kafka
ON report_model_tags_result_data_risk
COLUMNS(
    id,
    closed_rule_id,
    warning_time,
    warning_event_no,
    sounds_id,
    data_id,
    one_id,
    publish_time,
    event_name,
    subject_category_id,
    subject_category_name,
    event_priority,
    event_priority_name,
    event_level,
    event_level_name,
    confirmation_method,
    confirm_org_id,
    confirm_org_no,
    confirm_org_name,
    confirm_user_id,
    confirm_user_emp_no,
    confirm_user_name,
    review_method,
    review_org_id,
    review_org_no,
    review_org_name,
    review_user_id,
    review_user_emp_no,
    review_user_name,
    main_resp_org_id,
    main_resp_org_no,
    main_resp_org_name,
    main_resp_user_id,
    main_resp_user_emp_no,
    main_resp_user_name,
    cc_users,
    event_process_start_time,
    event_process_end_time,
    is_event_duplicate,
    is_processed,
    unprocessed_reason,
    process_description,
    review_progress_code,
    review_progress_name,
    review_handler_id,
    review_handler_name,
    review_content,
    private_msg_progress_code,
    private_msg_progress_name,
    private_msg_count,
    private_msg_channel,
    private_msg_details,
    related_work_order_nos,
    work_order_responder,
    old_work_order_responder,
    channel_code,
    channel_name,
    brand_code,
    brand_name,
    car_series_code,
    car_series_name,
    second_channel_code,
    second_channel_name,
    car_model,
    engine_no,
    license_plate_no,
    vin_no,
    car_purchase_time,
    dealer_name,
    dealer_code,
    content,
    content_type,
    original_text_scene,
    sentiment,
    intention_type,
    topic,
    dom_tag_first_code,
    dom_tag_second_code,
    dom_tag_three_code,
    dom_tag_four_code,
    dom_tag_first,
    dom_tag_second,
    dom_tag_three,
    dom_tag_four,
    comment_user_id,
    comment_user_name,
    comment_time,
    comment_details,
    is_main_post,
    main_post_title,
    main_post_details,
    post_user_id,
    post_user_name,
    post_time,
    main_post_url,
    sensitive_type,
    event_clarity,
    is_need_reply,
    is_need_closed_loop,
    update_time,
    create_time,
    update_user_id,
    task_status
)
PROPERTIES
(
    "enclose" = "\"",
    "escape" = "\\",
    "desired_concurrent_number" = "5",
    "format" = "json",
    "jsonpaths" = "[
        \"$.id\",
        \"$.closedRuleId\",
        \"$.warningTime\",
        \"$.warningEventNo\",
        \"$.soundsId\",
        \"$.dataId\",
        \"$.oneId\",
        \"$.publishTime\",
        \"$.eventName\",
        \"$.subjectCategoryId\",
        \"$.subjectCategoryName\",
        \"$.eventPriority\",
        \"$.eventPriorityName\",
        \"$.eventLevel\",
        \"$.eventLevelName\",
        \"$.confirmationMethod\",
        \"$.confirmOrgId\",
        \"$.confirmOrgNo\",
        \"$.confirmOrgName\",
        \"$.confirmUserId\",
        \"$.confirmUserEmpNo\",
        \"$.confirmUserName\",
        \"$.reviewMethod\",
        \"$.reviewOrgId\",
        \"$.reviewOrgNo\",
        \"$.reviewOrgName\",
        \"$.reviewUserId\",
        \"$.reviewUserEmpNo\",
        \"$.reviewUserName\",
        \"$.mainRespOrgId\",
        \"$.mainRespOrgNo\",
        \"$.mainRespOrgName\",
        \"$.mainRespUserId\",
        \"$.mainRespUserEmpNo\",
        \"$.mainRespUserName\",
        \"$.ccUsers\",
        \"$.eventProcessStartTime\",
        \"$.eventProcessEndTime\",
        \"$.isEventDuplicate\",
        \"$.isProcessed\",
        \"$.unprocessedReason\",
        \"$.processDescription\",
        \"$.reviewProgressCode\",
        \"$.reviewProgressName\",
        \"$.reviewHandlerId\",
        \"$.reviewHandlerName\",
        \"$.reviewContent\",
        \"$.privateMsgProgressCode\",
        \"$.privateMsgProgressName\",
        \"$.privateMsgCount\",
        \"$.privateMsgChannel\",
        \"$.privateMsgDetails\",
        \"$.relatedWorkOrderNos\",
        \"$.workOrderResponder\",
        \"$.oldWorkOrderResponder\",
        \"$.channelCode\",
        \"$.channelName\",
        \"$.secondChannelCode\",
        \"$.secondChannelName\",
        \"$.brandCode\",
        \"$.brandName\",
        \"$.carSeriesCode\",
        \"$.carSeriesName\",
        \"$.carModel\",
        \"$.engineNo\",
        \"$.licensePlateNo\",
        \"$.vinNo\",
        \"$.carPurchaseTime\",
        \"$.dealerName\",
        \"$.dealerCode\",
        \"$.content\",
        \"$.contentType\",
        \"$.originalTextScene\",
        \"$.sentiment\",
        \"$.intentionType\",
        \"$.topic\",
        \"$.domTagFirstCode\",
        \"$.domTagSecondCode\",
        \"$.domTagThreeCode\",
        \"$.domTagFourCode\",
        \"$.domTagFirst\",
        \"$.domTagSecond\",
        \"$.domTagThree\",
        \"$.domTagFour\",
        \"$.commentUserId\",
        \"$.commentUserName\",
        \"$.commentTime\",
        \"$.commentDetails\",
        \"$.isMainPost\",
        \"$.mainPostTitle\",
        \"$.mainPostDetails\",
        \"$.postUserId\",
        \"$.postUserName\",
        \"$.postTime\",
        \"$.mainPostUrl\",
        \"$.sensitiveType\",
        \"$.eventClarity\",
        \"$.isNeedReply\",
        \"$.isNeedClosedLoop\",
        \"$.updateTime\",
        \"$.createTime\",
        \"$.updateUserId\",
        \"$.taskStatus\"
    ]"
)
FROM KAFKA
(
    "kafka_broker_list" = "172.16.80.16:30092",
    "kafka_topic" = "voc_report_risk_data",
    "property.group.id" = "voc-report-risk",
    "property.kafka_default_offsets" = "OFFSET_BEGINNING"
);




CREATE ROUTINE LOAD report_rule_test_data_risk_result_kafka ON report_rule_test_data_risk_result
COLUMNS (
    id,
    rule_id,
    rule_name,
    data_id,
    batch_id,
    channel_name,
    channel_code,
    brand_name,
    brand_code,
    car_series_name,
    car_series_code,
    content_type,
    is_main_post,
    title,
    content,
    sentiment,
    intention,
    publish_time,
    dom_tag_first_code,
    dom_tag_second_code,
    dom_tag_three_code,
    dom_tag_four_code,
    dom_tag_first,
    dom_tag_second,
    dom_tag_three,
    dom_tag_four,
    topic_id,
    topic_text,
    publish_user_id,
    publish_user_nickname,
    main_post_user_id,
    main_post_user_name,
    create_time
)
PROPERTIES
(
    "enclose"="\"",
    "escape"="\\",
    "desired_concurrent_number" = "5",
    "format" = "json",
    "jsonpaths" = "[
        \"$.id\",
        \"$.ruleId\",
        \"$.ruleName\",
        \"$.dataId\",
        \"$.batchId\",
        \"$.channelName\",
        \"$.channelCode\",
        \"$.brandName\",
        \"$.brandCode\",
        \"$.carSeriesName\",
        \"$.carSeriesCode\",
        \"$.contentType\",
        \"$.isMainPost\",
        \"$.title\",
        \"$.content\",
        \"$.sentiment\",
        \"$.intention\",
        \"$.publishTime\",
        \"$.domTagFirstCode\",
        \"$.domTagSecondCode\",
        \"$.domTagThreeCode\",
        \"$.domTagFourCode\",
        \"$.domTagFirst\",
        \"$.domTagSecond\",
        \"$.domTagThree\",
        \"$.domTagFour\",
        \"$.topicId\",
        \"$.topicText\",
        \"$.publishUserId\",
        \"$.publishUserNickname\",
        \"$.mainPostUserId\",
        \"$.mainPostUserName\",
        \"$.createTime\"
    ]"
)
FROM KAFKA
(
    "kafka_broker_list" = "172.16.80.16:30092",
    "kafka_topic" = "voc_report_risk_data_test",
    "property.group.id" = "VDP-voc2-analysis",
    "property.kafka_default_offsets" = "OFFSET_BEGINNING"
);


