spring:
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      missing-topics-fatal: false
      auto-startup: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: voc-insights-standalone
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafkaEvent:
  groupId: voc-insights-standalone
