druid.mysql.usePingMethod: false

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      strict: false
      datasource:
        dndc:
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/vdp_ms_td?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
          username: root
          password: root
          hikari:
            minimum-idle: 2
            maximum-pool-size: 10
            auto-commit: true
            connection-timeout: 30000
            idle-timeout: 600000
            max-lifetime: 1800000
            validation-timeout: 5000
            pool-name: VocStandaloneClientPool
