apply plugin: 'java-library'

group = 'voc-mpp'
version = "2.0.0-SNAPSHOT"

dependencies {
    testImplementation  project(':voc-service-common').sourceSets.test.output
    api project(':voc-service-common')
    api project(':voc-service-security:voc-security-api')
    api project(':voc-service-insights:voc-insights-api')
    api project(':voc-service-analysis:voc-analysis-api')
    api project(':voc-service-data-integration:voc-data-integration-api')
    api project(':voc-service-config')
    api project(':voc-service-components:voc-cmps-redis')
    api project(':voc-service-components:voc-cmps-mybatis')
    api project(':voc-service-components:voc-cmps-xxljob')
    api project(':voc-service-components:voc-cmps-kafka')

    compileOnly('org.springframework.boot:spring-boot-starter-web')
    api('org.springframework.cloud:spring-cloud-starter-bootstrap')
    api ("com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery")
    api ("com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config")
    api('com.github.pagehelper:pagehelper-spring-boot-starter')
    api('com.baomidou:mybatis-plus-boot-starter')
    api('com.yomahub:liteflow-spring-boot-starter'){
        exclude group: 'org.yaml', module: 'snakeyaml'
    }
    api('com.yomahub:liteflow-el-builder'){
        exclude group: "cn.hutool", module: "hutool-core"
    }
    api('com.xuxueli:xxl-job-core')
}

